### ISSUE TITLE
screen is not updating until if that screen is not render 

### ISSUE THREAD

**Issue by mrvyas417** [cwkProject/action_broadcast#1]
I have a dashboard file. In this file, I've registered a broadcast. I created three tabs: sales, network, and market. Each tab has its own separate code file. I send a broadcast from the dashboard file to all the tabs. However, only the active tab receives and updates the broadcast. Additionally, I have another file that acts as a filter. From this filter file, I'm sending some values using the "sendbroadcast" function. This broadcast is registered in the dashboard file, and the values received from the filter are then forwarded through the broadcast to all three tabs. Yet, only the currently active tab reflects the updated values.

Dashbaord.dart file :- 

  @override
  Iterable<StreamSubscription> get registerSubscriptions sync* {
    yield registerReceiver([Const.all, Const.selected]).listen(
      (intent) {
        switch (intent.action) {
          case Const.all:
            SOFilterValue = intent.data["SO"];

            DOFilterValue = intent.data["DO"];
            SelectedIndexForSO = intent.data["SelectedIndexForSO"];
            SelectedIndexForDO = intent.data["SelectedIndexForDO"];
            setState(() {});
            sendBroadcast(Const.updateSalesTabActualTargetWidget, data: {
              "SO": SOFilterValue,
              "DO": DOFilterValue,
            });
            sendBroadcast(Const.updateMarket, data: {
              "SO": SOFilterValue,
              "DO": DOFilterValue,
            });
            break;
          case Const.selected:
            SOFilterValue = intent.data["SO"];

            DOFilterValue = intent.data["DO"];
            SelectedIndexForSO = intent.data["SelectedIndexForSO"];
            SelectedIndexForDO = intent.data["SelectedIndexForDO"];
            setState(() {});
            sendBroadcast(Const.updateSalesTabActualTargetWidget, data: {
              "SO": SOFilterValue,
              "DO": DOFilterValue,
            });
            sendBroadcast(Const.updateMarket, data: {
              "SO": SOFilterValue,
              "DO": DOFilterValue,
            });
            //    print("objx after  ${SOFilterValue!.userName}");

            break;

          default:
        }
      },
    );
  }

  _body(BuildContext context) {
    return SingleChildScrollView(
      child: Stack(
        children: [
          Container(
            padding: const EdgeInsets.fromLTRB(24, 20, 24, 0),
            width: double.infinity,
            child: Column(
              mainAxisAlignment: MainAxisAlignment.start,
              crossAxisAlignment: CrossAxisAlignment.start,
              mainAxisSize: MainAxisSize.max,
              children: [
                Padding(
                  padding: const EdgeInsets.all(8.0),
                  child: _dateAndTimeComponent(),
                ),
                SizedBox(
                  width: double.infinity,
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      _tabs(
                          title: "Sales",
                          onpress: () {
                            setState(() {
                              activeTab = "Sales";
                            });
                          }),
                      _tabs(
                          title: "Market",
                          onpress: () {
                            setState(() {
                              activeTab = "Market";
                            });
                          }),
                      _tabs(
                          title: "Network",
                          onpress: () {
                            setState(() {
                              activeTab = "Network";
                            });
                          }),
                    ],
                  ),
                ),
                const SizedBox(
                  height: 10,
                ),
                _tabRoutes(),
              ],
            ),
          ),
          Positioned(
            right: -5.0,
            top: 250,
            child: GestureDetector(
              onTap: () {},
              child: Image.asset(
                "images/new_cart.png",
              ),
            ),
          ),
        ],
      ),
    );
  }

**Comment by 39251474** [comment]
这是`flutter  widget` 生命周期机制导致的结果。
当`widget`不被构建时`widget`实例就会被立即销毁，内存会被释放，通过`registerSubscriptions`注册的广播也会随`widget`的销毁一同注销。如果强制不注销广播也会导致内存泄漏，相同广播代码重复注册等问题出现，广播注册和注销必须配对，依赖的`widget`实例销毁时也必须对应注销广播。通过`AutoCancelStreamMixin.registerSubscriptions`注册的广播会自动注销。

你遇到的问题关键点在于如何让`StatefullWidget`的`state`保活。你需要学习一下相关`widget`，比如`AutomaticKeepAliveClientMixin`，并配合`PageView`，`TabBarView`等组件。

**Comment by mrvyas417** [comment]
can you write in English

**Comment by 39251474** [comment]
我不擅长英语，你可以用Google Translate or ChatGPT

**Comment by mrvyas417** [comment]
Thanks I use TabBarView and now its working
